// Captures the desktop launcher's session-restore view for the docs: seeds a
// three-project session into an isolated profile, boots the real Electron app
// through a shim entry, and screenshots the launcher mid-restore.
import { execFileSync } from 'node:child_process';
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync
} from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import workspaceRoot from './workspace-root.js';

const require = createRequire(import.meta.url);
const { _electron } = require('playwright-core');

const here = dirname(fileURLToPath(import.meta.url));
const desktopDir = join(here, '..', 'desktop');
const outputPath = join(
  here,
  '..',
  'docs',
  'src',
  'assets',
  'screenshots',
  'restore.png'
);

const runtimeJupyter = join(desktopDir, 'python', 'runtime', 'bin', 'jupyter');
if (!existsSync(runtimeJupyter)) {
  console.error(
    `Missing the desktop Python runtime at ${dirname(runtimeJupyter)}.\n` +
      'Build it once with: pnpm -C ../desktop build:all'
  );
  process.exit(1);
}

// dist/ must match the sources, so the TypeScript build reruns each capture.
execFileSync(
  process.execPath,
  [
    join(desktopDir, 'node_modules', 'typescript', 'bin', 'tsc'),
    '-p',
    join(desktopDir, 'tsconfig.json')
  ],
  { stdio: 'inherit' }
);

// The same seeded workspace the web captures use, plus two sibling projects
// so the restore lists three windows from one native tab group.
execFileSync(process.execPath, [join(here, 'seed-workspace.mjs')], {
  stdio: 'inherit'
});
const extraProjects = ['sales-dashboard', 'ml-experiments'];
for (const name of extraProjects) {
  cpSync(join(here, 'fixtures', 'restore-projects', name), join(workspaceRoot, name), {
    recursive: true
  });
}

const userDataDir = join(workspaceRoot, 'desktop-userdata');
rmSync(userDataDir, { recursive: true, force: true });
mkdirSync(userDataDir, { recursive: true });

// One groupId + identical bounds restore the three windows as native tabs of
// a single window; demo-project's highest focusSequence leaves it selected.
const groupId = '5d0aa1de-6d05-4bb2-9f6c-1f1f6f8f2a10';
const bounds = { x: 80, y: 80, width: 1280, height: 860 };
const sessionState = {
  version: 1,
  windows: [
    { folderPath: join(workspaceRoot, 'demo-project'), focusSequence: 3 },
    { folderPath: join(workspaceRoot, 'sales-dashboard'), focusSequence: 1 },
    { folderPath: join(workspaceRoot, 'ml-experiments'), focusSequence: 2 }
  ].map(window => ({
    ...window,
    groupId,
    bounds,
    maximized: false,
    fullScreen: false
  }))
};
writeFileSync(
  join(userDataDir, 'session-state.json'),
  `${JSON.stringify(sessionState, null, 2)}\n`,
  'utf8'
);

// A generated shim app relocates the profile before the real main module
// runs, so the capture never touches a real profile or its single-instance lock.
const desktopVersion = JSON.parse(
  readFileSync(join(desktopDir, 'package.json'), 'utf8')
).version;
const shimDir = join(workspaceRoot, 'desktop-shim');
rmSync(shimDir, { recursive: true, force: true });
mkdirSync(shimDir, { recursive: true });
// The launcher footer shows app.getVersion(), which reads this manifest.
writeFileSync(
  join(shimDir, 'package.json'),
  `${JSON.stringify(
    {
      name: 'xtralab-desktop-capture',
      private: true,
      version: desktopVersion,
      main: 'shim.cjs'
    },
    null,
    2
  )}\n`,
  'utf8'
);
writeFileSync(
  join(shimDir, 'shim.cjs'),
  `// Generated by ui-tests/desktop-restore.mjs.
const { app, nativeTheme } = require('electron');
app.setPath('userData', ${JSON.stringify(userDataDir)});
// The documentation screenshots are all dark.
nativeTheme.themeSource = 'dark';
require(${JSON.stringify(join(desktopDir, 'dist', 'main.js'))});
`,
  'utf8'
);

const electronApp = await _electron.launch({
  executablePath: createRequire(join(desktopDir, 'package.json'))('electron'),
  args: [shimDir]
});

try {
  // All three lab pages load within milliseconds of each other; holding the
  // two non-leader page loads keeps their rows mid-restore until the capture.
  const heldRoutes = [];
  await electronApp.context().route(/\/lab\/workspaces\//, route => {
    if (route.request().url().includes('demo-project')) {
      void route.continue();
      return;
    }
    heldRoutes.push(route);
  });

  let launcher;
  const launcherDeadline = Date.now() + 30_000;
  while (launcher === undefined) {
    launcher = electronApp
      .windows()
      .find(page => page.url().endsWith('launcher.html'));
    if (launcher === undefined) {
      if (Date.now() > launcherDeadline) {
        throw new Error('The launcher window never appeared');
      }
      await new Promise(resolve => setTimeout(resolve, 100));
    }
  }

  // Playwright emulates a light color scheme by default, which would
  // override the dark nativeTheme the shim sets.
  await launcher.emulateMedia({ colorScheme: 'dark' });

  await launcher.waitForSelector('#restore-view:not(.is-inactive)', {
    timeout: 30_000
  });

  // A clean restore closes the launcher, so finishing early or a failed row
  // both abort the capture.
  const captureDeadline = Date.now() + 120_000;
  for (;;) {
    let statuses;
    try {
      statuses = await launcher.evaluate(() =>
        [...document.querySelectorAll('.restore-status')].map(
          element => element.dataset.status
        )
      );
    } catch (error) {
      throw new Error(
        `The launcher closed before the capture (restore finished too fast): ${error}`
      );
    }
    if (statuses.includes('failed')) {
      throw new Error(
        `A project failed to restore (${statuses.join(', ')}); ` +
          `check the logs under ${userDataDir}`
      );
    }
    const opened = statuses.filter(status => status === 'opened').length;
    if (opened > 0 && opened < statuses.length) {
      break;
    }
    if (statuses.length > 0 && opened === statuses.length) {
      throw new Error('The restore finished before the capture');
    }
    if (Date.now() > captureDeadline) {
      throw new Error(`Timed out waiting for restore progress (${statuses.join(', ')})`);
    }
    await new Promise(resolve => setTimeout(resolve, 40));
  }

  // Let the progress bar's width transition settle before capturing; the
  // held page loads keep the state itself from advancing.
  await new Promise(resolve => setTimeout(resolve, 400));
  await launcher.screenshot({ path: outputPath, scale: 'device' });
  console.log(`Captured ${outputPath}`);

  for (const route of heldRoutes) {
    void route.continue().catch(() => {});
  }
} finally {
  await electronApp.evaluate(({ app }) => app.quit()).catch(() => {});
  await electronApp.close().catch(() => {});
}
